# Generated by Django 3.1.3 on 2020-11-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='motivation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
